// для карточки
export const INPUT_CHOOSE_CARD = 'INPUT_CHOOSE_CARD'; // +
export const INPUT_NAME_DESCRIPTION_CARD = 'INPUT_NAME_DESCRIPTION_CARD'; // +
export const STATUS_CREATING_CARD = 'STATUS_CREATING_CARD'; // +
export const SET_RESPONCE_ID = 'SET_RESPONCE_ID'; // +
// ////////////////////////////////////////////

// для статьи
export const CHANGE_STATUS_CREATING_ARTICLE = 'CHANGE_STATUS_CREATING_ARTICLE'; // +
export const RESET_COMPONENT_TO_ARTICLE = 'RESET_COMPONENT_TO_ARTICLE'; // +
export const RESET_PREVIEW_CONTENT_AN_ARTICLE = 'RESET_PREVIEW_CONTENT_AN_ARTICLE'; // +

export const CHANGE_BAN_ADD_ELEMENT = 'CHANGE_BAN_ADD_ELEMENT'; // ?

export const CURRENT_TAG_BUTTON = 'CURRENT_TAG_BUTTON'; // +
export const ADD_PREVIEW_CONTENT_AN_ARTICLE = 'ADD_PREVIEW_CONTENT_AN_ARTICLE'; // +
export const ADD_ID_FOR_NEW_ELEMENT = 'ADD_ID_FOR_NEW_ELEMENT'; // +
export const UPDATE_PREVIEW_CONTENT_AN_ARTICLE = 'UPDATE_PREVIEW_CONTENT_AN_ARTICLE';
// ////////////////////////////////////////////
export const FILTER_PREVIEW_CONTENT_AN_ARTICLE = 'FILTER_PREVIEW_CONTENT_AN_ARTICLE';
export const DELETED_COMPONENT_ID = 'DELETED_COMPONENT_ID';

export const ADD_COMPONENT_TO_ARTICLE = 'ADD_COMPONENT_TO_ARTICLE';
export const DELETE_PREVIEW_CONTENT_FROM_ARTICLE = 'DELETE_PREVIEW_CONTENT_FROM_ARTICLE';
export const ADD_PREVIEW_CONTENT_AN_ARTICLE_AFTER_EDIT = 'ADD_PREVIEW_CONTENT_AN_ARTICLE_AFTER_EDIT';
export const MINUS_ID_FOR_NEW_ELEMENT = 'MINUS_ID_FOR_NEW_ELEMENT';
export const CHANGE_ID_ALL_PREVIEW_ELEMENTS = 'CHANGE_ID_ALL_PREVIEW_ELEMENTS';
export const HOVER_INDEX_ELEMENT = 'HOVER_INDEX_ELEMENT';
export const STATUS_CLICK_PANEL_TAGS = 'STATUS_CLICK_PANEL_TAGS';
export const AFTER_ADDED_TO_REVIEW_CONTENT_ARTICLE = 'AFTER_ADDED_TO_REVIEW_CONTENT_ARTICLE';

//для просмотра всех карт и статьи
export const GET_ALL_CARDS = 'GET_ALL_CARDS';
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';

export const OBSERVE_CHANGES = 'OBSERVE_CHANGES';